---
- hosts:
    all
  gather_facts: yes
  vars:
    verbose: false
    log_dir: "log/dist-upgrade/{{ inventory_hostname }}"

  tasks:
    - name: Download Zabbix.deb
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb
        dest: /root
    - name: Install Zabbix.de
      command: dpkg -i /root/zabbix-release_6.4-1+debian12_all.deb
    - name: install zabbix-agent2
      ansible.builtin.apt:
        name: zabbix-agent2
        update_cache: yes
