---
- hosts:
    all
  gather_facts: yes
  vars:
    verbose: false
    log_dir: "log/dist-upgrade/{{ inventory_hostname }}"

  tasks:
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      
    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
