---
- hosts: all
  tasks:
    - name: Prepare. Autoremove old packages
      apt:
        autoremove: true
        clean: true

    - name: Upgrade to latest release (apt-get dist-upgrade)
      ansible.builtin.shell: |
        sed -i 's/bullseye/bookworm/g' /etc/apt/sources.list
        sed -i 's/non-free non-free-firmware-firmware//g' /etc/apt/sources.list
        if ! grep non-free-firmware /etc/apt/sources.list
        then
            sed -i 's/non-free/non-free non-free-firmware/g' /etc/apt/sources.list
        fi

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 0

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
