---
- hosts: all
  tasks:
    - name: Prepare. Autoremove old packages
      apt:
        autoremove: true
        clean: true
#
#    - name: Upgrade to latest release (apt-get dist-upgrade)
#      ansible.builtin.shell: |
#        sed -i 's/6.4/7.0/g' /etc/apt/sources.list.d/zabbix.list
    - name: Download Zabbix.deb
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb
        dest: /root
    - name: remove old zabbix.list
      command: rm -Rf /etc/apt/sources.list.d/zabbix.list
    - name: Install Zabbix.de
      command: dpkg -i --force-overwrite /root/zabbix-release_latest+debian12_all.deb

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 0

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
