---
- hosts: all
  gather_facts: yes
  become: false
  tasks:  
    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
      win_updates:
        category_names: Application, Connectors, Critical Updates, Definition Updates, Developer Kits, Feature Packs, Guidance, Security Updates, Service Packs, Tools, Update Rollups, Updates
        state: searched
        log_path: C:\ansible_wu.txt
        server_selection: windows_update
    - name: Install selected Update
      win_updates:
        category_names: Application, Connectors, Critical Updates, Definition Updates, Developer Kits, Feature Packs, Guidance, Security Updates, Service Packs, Tools, Update Rollups, Updates
        log_path: C:\ansible_wu.txt
        server_selection: windows_update
        accept_list: {{update}}
