---
- hosts: all
  gather_facts: yes
  ignore_unreachable: true
  tasks:  
    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
      win_updates:
        category_names: Application, Connectors, Critical Updates, Definition Updates, Developer Kits, Feature Packs, Guidance, Security Updates, Service Packs, Tools, Update Rollups, Updates, Drivers
        #state: searched
        log_path: C:\ansible_wu_missing.txt
        server_selection: windows_update
      register: contains
    - name: Send data to server
      ansible.builtin.uri:
        url: {{server}}
        method: POST
        body: {{contains}}
        body_format: json
        headers:
          Content-Type: application/json
#    - debug: var=contains
#    - name: Install selected Update
#      win_updates:
#        category_names: Application, Connectors, Critical Updates, Definition Updates, Developer Kits, Feature Packs, Guidance, Security Updates, Service Packs, Tools, Update Rollups, Updates
#        log_path: C:\ansible_wu_install.txt
#        server_selection: windows_update
