---
- name: Identify reachable hosts
  hosts: all
  connection: local
  tasks:
    - block:
        - name: determine hosts that are reachable
          ansible.builtin.wait_for_connection:
            timeout: 10
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "reachable" group
          ansible.builtin.group_by:
            key: reachable
      rescue:
        - name: debug print unreachable host(s)
          ansible.builtin.debug: msg="cannot connect to {{ inventory_hostname }}"

- name: Provision reachable hosts
  hosts: reachable
  gather_facts: no
  #ignore_unreachable: true
  #strategy: free    
  tasks:
  - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
    block:
    - name: Search
      ignore_unreachable: true
      win_updates:
        category_names: Application, Connectors, Critical Updates, Definition Updates, Developer Kits, Feature Packs, Guidance, Security Updates, Service Packs, Tools, Update Rollups, Updates, Drivers
          #        state: searched
        log_path: C:\ansible_wu_missing.txt
        server_selection: windows_update
      register: contains
    rescue:
    - name: Some thing gone wrong
      ansible.windows.win_uri:
        url: "{{server}}"
        method: POST
        body: "{'host':'{{inventory_hostname}}' , 'data':FAILD}"

  - name: POST a Body to an Endpoint
    ansible.windows.win_uri:
      url: "{{server}}"
      method: POST
      force_basic_auth: true
      url_username: "{{url_user}}"
      url_password: "{{url_pass}}"
      content_type: application/json
      body: "{'host':'{{inventory_hostname}}' , 'data':{{contains.updates}}, 'reboot':'{{contains.reboot_required}}'}"

